### PR TITLE
Upgrade pulumi version to 3.0.0 in node test

### PR DESCRIPTION
**Pull request by guineveresaenger**
Fixes failing build on default branch.

### CODE REVIEW

**Comment by t0yv0** [comment]
This is duplicative of https://github.com/pulumi/pulumi-akamai/pull/126 which now performs this change automatically from ci-mgmt. I wonder why the PR verification for that PR failed though. Let me try to restart that to see if it's a transient failure.

**Comment by guineveresaenger** [comment]
I'm still seeing this: https://github.com/pulumi/pulumi-akamai/blob/master/examples/edge-hostname/ts/package.json#L7 but perhaps that is overridden in examples tests now?

**Comment by t0yv0** [comment]
Had a quick look. No it's not done yet it seems - because pulumi/ci-mgmt#307 has not yet been merged. I'll merge this PR for now, but please don't make this kind of change by hand if you see more of it - a better way for us to do this kind of change is:

1. Review and merge https://github.com/pulumi/ci-mgmt/pull/307
2. If something else similarly needs to roll out across examples, write another source migration in ci-mgmt, PR and merge it
3. Run ci-mgmt action to stand up PR across all provider repos
4. Enjoy it rolling out everywhere

:)

**Review by t0yv0 — APPROVED** [review]

**Comment by guineveresaenger** [comment]
I agree this should be automated. Will take a look at pulumi/ci-mgmt#307. 👍

**Pull request merged**
